// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConversationBase
 */
export type ConversationBase = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ConversationListResponse
 */
export type ConversationListResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Conversations
     */
    conversations: Array<ConversationBase>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetConversationsApiUsersUserIdConversationsGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/conversations';
};

export type GetConversationsApiUsersUserIdConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationsApiUsersUserIdConversationsGetError = GetConversationsApiUsersUserIdConversationsGetErrors[keyof GetConversationsApiUsersUserIdConversationsGetErrors];

export type GetConversationsApiUsersUserIdConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationListResponse;
};

export type GetConversationsApiUsersUserIdConversationsGetResponse = GetConversationsApiUsersUserIdConversationsGetResponses[keyof GetConversationsApiUsersUserIdConversationsGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8002' | (string & {});
};