// This file is auto-generated by @hey-api/openapi-ts

/**
 * ConversationBase
 */
export type ConversationBase = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ConversationListResponse
 */
export type ConversationListResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Conversations
     */
    conversations: Array<ConversationBase>;
};

/**
 * CreateMessageRequest
 */
export type CreateMessageRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageBase
 */
export type MessageBase = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
};

/**
 * MessageListResponse
 */
export type MessageListResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Messages
     */
    messages: Array<MessageBase>;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Success
     */
    success: boolean;
    message: MessageBase;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetConversationsApiUsersUserIdConversationsGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/conversations';
};

export type GetConversationsApiUsersUserIdConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationsApiUsersUserIdConversationsGetError = GetConversationsApiUsersUserIdConversationsGetErrors[keyof GetConversationsApiUsersUserIdConversationsGetErrors];

export type GetConversationsApiUsersUserIdConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationListResponse;
};

export type GetConversationsApiUsersUserIdConversationsGetResponse = GetConversationsApiUsersUserIdConversationsGetResponses[keyof GetConversationsApiUsersUserIdConversationsGetResponses];

export type GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/conversations/{conversation_id}/messages';
};

export type GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetError = GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetErrors[keyof GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetErrors];

export type GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: MessageListResponse;
};

export type GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponse = GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponses[keyof GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponses];

export type CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostData = {
    body: CreateMessageRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/conversations/{conversation_id}/message';
};

export type CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostError = CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostErrors[keyof CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostErrors];

export type CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponse = CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponses[keyof CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8002' | (string & {});
};